# Generated by Django 3.2.9 on 2021-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject of the Complaint')),
                ('message', models.TextField()),
            ],
        ),
    ]
